# Numpy

In [1]:
#Numarical Python 
# general purpose Array processosing python 
# Numpy : numbers based access
#pandas : full access , Internally stores in numpy array only. 
# Numpy , pandas, matplolib , Seaborn 

In [2]:
#Numpy is core library for scintific computing in python , Gereral purpse array processing package. 

In [3]:
# Axis --->>>>> ID Array , 2 D Array , 3 D Array 
# Shape(4) shape (2,3) shape(4,3,2) can be N dimensions as every new catagory gives you new dimension 

# Creation of matrix

In [23]:
import numpy as np
mylist1 = [11,22,33,44,55,66]
n1 = np.array(mylist1)
print(n1)
print(n1.size)
print(n1.shape)
print(n1)
print(n1.dtype) # is importent
print(n1.itemsize)

[11 22 33 44 55 66]
6
(6,)
[11 22 33 44 55 66]
int64
8


In [28]:
import numpy as np
mylist1 = [11,22,33,44,55,66]
n1 = np.array(mylist1,dtype=int)
print(n1)
print(n1.size)
print(n1.shape)
print(n1)
print(n1.dtype)
print(n1.itemsize)

[11 22 33 44 55 66]
6
(6,)
[11 22 33 44 55 66]
int64
8


In [37]:
# create Manual array 
list2= [
    [11,22,33],
    [44,55,66]
]
import numpy as np
n1 = np.array(list2,dtype=int)
print(n1)
print(n1.size)
print(n1.shape)
print(n1)
print(n1.dtype)
print(n1.itemsize)

[[11 22 33]
 [44 55 66]]
6
(2, 3)
[[11 22 33]
 [44 55 66]]
int64
8


In [44]:
#create 3 d Array 
list3 = [
    [[111,121],[141,151],[171,181]],
    [[211,221],[241,251],[271,281]],
    [[311,321],[341,351],[371,381]],
    [[411,421],[441,451],[471,481]],
]
import numpy as np
n2 = np.array(list3,dtype=int)
print(n2)
print(n2.size)
print(n2.shape)
print(n2)
print(n2.dtype)
print(n2.itemsize)

[[[111 121]
  [141 151]
  [171 181]]

 [[211 221]
  [241 251]
  [271 281]]

 [[311 321]
  [341 351]
  [371 381]]

 [[411 421]
  [441 451]
  [471 481]]]
24
(4, 3, 2)
[[[111 121]
  [141 151]
  [171 181]]

 [[211 221]
  [241 251]
  [271 281]]

 [[311 321]
  [341 351]
  [371 381]]

 [[411 421]
  [441 451]
  [471 481]]]
int64
8


# arange

In [57]:

sadf

NameError: name 'sadf' is not defined

In [62]:
n2 = np.arange(12)
n34 = n2.reshape(3,4)
n34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
n5 = np.arange(12)
#arange always return 1d entitity which you could reshape using reshape Function 


n1= np.arange(48)
n642= n1.reshape(6,4,-1)
n642.shape

In [75]:
np.random.seed(23)
n1 = np.random.randint(low=0,high=100,size=(48,))
print(n1.shape)
n1

(48,)


array([83, 40, 73, 54, 31, 76, 91, 39, 90, 25, 51,  6, 45, 12, 49, 66, 75,
       85, 69, 64, 12, 21, 48, 41, 79, 90, 62, 57, 19, 33, 59, 39, 15, 36,
       65,  1, 43, 15, 86, 83, 58, 25, 66, 74, 35, 96, 56, 13])

In [77]:
np.random.seed(23)
n1 = np.random.randint(low=0,high=100,size=(6,4))
print(n1.shape)
n1

(6, 4)


array([[83, 40, 73, 54],
       [31, 76, 91, 39],
       [90, 25, 51,  6],
       [45, 12, 49, 66],
       [75, 85, 69, 64],
       [12, 21, 48, 41]])

In [80]:
# Arthematics operations on Arran1 
n1 = np.arange(12)
print(n1)
n1 + 10

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [90]:
n34a = np.arange(12).reshape(3,4)
print(n34a)
n34b = np.arange(12).reshape(3,4)
print(n34b)
n34a + n34b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [98]:
openprice = np.random.randint(low=0,high=100,size=(6,2))
closeprice = np.random.randint(low=0,high=100,size=(6,2))
volatility = closeprice - openprice
volatility

array([[ 28,   1],
       [ 12, -33],
       [ 52, -24],
       [ 11,   4],
       [ -5, -20],
       [ 56,  72]])

In [102]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89


array([[83, 40, 73, 54, 31, 76, 91, 39, 90],
       [25, 51,  6, 45, 12, 49, 66, 75, 85],
       [69, 64, 12, 21, 48, 41, 79, 90, 62],
       [57, 19, 33, 59, 39, 15, 36, 65,  1],
       [43, 15, 86, 83, 58, 25, 66, 74, 35],
       [96, 56, 13, 60, 22, 38, 31, 94, 78],
       [ 0, 21,  6, 32, 98, 32, 14, 31, 78],
       [83, 80, 70, 66, 82, 85, 55, 27, 62]])

In [104]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[0][0] 

83

In [106]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[0,0] # loosely 


83

In [107]:
#n89[row_index]
#n89[row_index,colum_index]

NameError: name 'row_index' is not defined

In [110]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[0,0] # loosely 
n89[1:6,3:6]

array([[45, 12, 49],
       [21, 48, 41],
       [59, 39, 15],
       [83, 58, 25],
       [60, 22, 38]])

In [112]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[0,0] # loosely 
n89[[0,2,3,-1,-2]]
#Grammer n89[[list of rows]]

array([[83, 40, 73, 54, 31, 76, 91, 39, 90],
       [69, 64, 12, 21, 48, 41, 79, 90, 62],
       [57, 19, 33, 59, 39, 15, 36, 65,  1],
       [83, 80, 70, 66, 82, 85, 55, 27, 62],
       [ 0, 21,  6, 32, 98, 32, 14, 31, 78]])

In [116]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[[0,1,2],[-3,-2,-1]]

array([91, 75, 62])

In [119]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[:,[2,5,6]]

array([[73, 76, 91],
       [ 6, 49, 66],
       [12, 41, 79],
       [33, 15, 36],
       [86, 25, 66],
       [13, 38, 31],
       [ 6, 32, 14],
       [70, 85, 55]])

In [126]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[1:5,[5]]#Grammer is impartant 

array([[49],
       [41],
       [15],
       [25]])

# Conditional Access

In [129]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
#get all values > 15 
mask = n89 > 50
n89[mask]

array([83, 73, 54, 76, 91, 90, 51, 66, 75, 85, 69, 64, 79, 90, 62, 57, 59,
       65, 86, 83, 58, 66, 74, 96, 56, 60, 94, 78, 98, 78, 83, 80, 70, 66,
       82, 85, 55, 62])