In [1]:
#Numarical Python
#genral purpose array procesing python
#numpy number based access
#pandas full access internally stores in numpy array only
#Numpy is core library for scientific computing gernal purpose array processing.


In [2]:
#ASIX >>>>> ID ARRAY ,2 D ARRAY , 3 D RRAY 

#SHAPE (4) shape(2,4) shape (4,3,2)


In [10]:
import numpy as np
mylist1=[11,22,33,44,55,66]
n1=np.array(mylist1)
print(n1.size)
print(n1.shape)
print(n1.itemsize)

6
(6,)
8


In [23]:
#creation of matrix
list1 = [
    [11,22,33],
    [44,55,66]
]
list1
n2=np.array(list1)
n2[0:2]

array([[11, 22, 33],
       [44, 55, 66]])

In [29]:
#arange
n1=np.arange(12)
n1
n2=n1.reshape(3,4)
n2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
np.random.seed(23)
n1=np.random.randint(low=0,high=99,size=(6,4))
n1

array([[83, 40, 73, 54],
       [31, 76, 91, 39],
       [90, 25, 51,  6],
       [45, 12, 49, 66],
       [75, 85, 69, 64],
       [12, 21, 48, 41]])

In [40]:
n1[0]

array([83, 40, 73, 54])

In [66]:
np.random.seed(23)
n1=np.random.randint(low=0,high=99,size=(8,9))
n1

array([[83, 40, 73, 54, 31, 76, 91, 39, 90],
       [25, 51,  6, 45, 12, 49, 66, 75, 85],
       [69, 64, 12, 21, 48, 41, 79, 90, 62],
       [57, 19, 33, 59, 39, 15, 36, 65,  1],
       [43, 15, 86, 83, 58, 25, 66, 74, 35],
       [96, 56, 13, 60, 22, 38, 31, 94, 78],
       [ 0, 21,  6, 32, 98, 32, 14, 31, 78],
       [83, 80, 70, 66, 82, 85, 55, 27, 62]])

In [68]:
n1[1:6,3:6]

array([[45, 12, 49],
       [21, 48, 41],
       [59, 39, 15],
       [83, 58, 25],
       [60, 22, 38]])

In [58]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89
n89[0,0] # loosely 
#Grammer n89[[list of rows]]

83

In [73]:
    n89[[0,1,-1,-2]]

array([[83, 40, 73, 54, 31, 76, 91, 39, 90],
       [25, 51,  6, 45, 12, 49, 66, 75, 85],
       [83, 80, 70, 66, 82, 85, 55, 27, 62],
       [ 0, 21,  6, 32, 98, 32, 14, 31, 78]])

In [79]:
    n89[[0,1,-1,-2],[4]]

array([31, 12, 82, 98])

In [81]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89


array([[83, 40, 73, 54, 31, 76, 91, 39, 90],
       [25, 51,  6, 45, 12, 49, 66, 75, 85],
       [69, 64, 12, 21, 48, 41, 79, 90, 62],
       [57, 19, 33, 59, 39, 15, 36, 65,  1],
       [43, 15, 86, 83, 58, 25, 66, 74, 35],
       [96, 56, 13, 60, 22, 38, 31, 94, 78],
       [ 0, 21,  6, 32, 98, 32, 14, 31, 78],
       [83, 80, 70, 66, 82, 85, 55, 27, 62]])

In [82]:
n89[:,[2,5,6]]

array([[73, 76, 91],
       [ 6, 49, 66],
       [12, 41, 79],
       [33, 15, 36],
       [86, 25, 66],
       [13, 38, 31],
       [ 6, 32, 14],
       [70, 85, 55]])

In [83]:
np.random.seed(23)
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89

array([[83, 40, 73, 54, 31, 76, 91, 39, 90],
       [25, 51,  6, 45, 12, 49, 66, 75, 85],
       [69, 64, 12, 21, 48, 41, 79, 90, 62],
       [57, 19, 33, 59, 39, 15, 36, 65,  1],
       [43, 15, 86, 83, 58, 25, 66, 74, 35],
       [96, 56, 13, 60, 22, 38, 31, 94, 78],
       [ 0, 21,  6, 32, 98, 32, 14, 31, 78],
       [83, 80, 70, 66, 82, 85, 55, 27, 62]])

In [91]:
n89[1:5,[5]]

array([[49],
       [41],
       [15],
       [25]])

In [93]:
#conditional acces numpy : 

In [105]:
np.random.seed(23)
n89=np.random.randint(low=4,high=99,size=(8,9))
mask=n89 <90
n89[n89 < 70]


array([44, 58, 35, 43, 29, 55, 10, 49, 16, 53, 68, 16, 25, 52, 45, 66, 61,
       23, 37, 63, 43, 19, 40, 69,  5, 47, 19, 62, 29, 39, 60, 17, 64, 26,
       42, 35,  4, 25, 10, 36, 36, 18, 35, 59, 31, 66, 47])

In [108]:

mask2=  n89 < 90
mask2

array([[ True,  True,  True,  True,  True,  True, False,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [119]:
np.random.seed(23)
n89=np.random.randint(low=0,high=100,size=(8,9))
n89[0]
n89[n89 < 90]=89
n89

array([[89, 89, 89, 89, 89, 89, 91, 89, 90],
       [89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 90, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89],
       [96, 89, 89, 89, 89, 89, 89, 94, 89],
       [89, 89, 89, 89, 98, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89]])

In [121]:

np.random.seed(23)
n89=np.random.randint(low=0,high=100,size=(8,9))
n89


array([[83, 40, 73, 54, 31, 76, 91, 39, 90],
       [25, 51,  6, 45, 12, 49, 66, 75, 85],
       [69, 64, 12, 21, 48, 41, 79, 90, 62],
       [57, 19, 33, 59, 39, 15, 36, 65,  1],
       [43, 15, 86, 83, 58, 25, 66, 74, 35],
       [96, 56, 13, 60, 22, 38, 31, 94, 78],
       [ 0, 21,  6, 32, 98, 32, 14, 31, 78],
       [83, 80, 70, 66, 82, 85, 55, 27, 62]])

In [129]:
n34=np.arange(12)
n34.reshape(3,4).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [136]:
n36=np.arange(100,118).reshape(3,6)
n36

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117]])

In [142]:

# Create two 1-dimensional arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Vertically stack the arrays
result = np.hstack((array1, array2))

print(result)

[1 2 3 4 5 6]


In [146]:
n64=np.arange(200,224).reshape(6,4)
n64


array([[200, 201, 202, 203],
       [204, 205, 206, 207],
       [208, 209, 210, 211],
       [212, 213, 214, 215],
       [216, 217, 218, 219],
       [220, 221, 222, 223]])

In [151]:
n94 = np.arange(0,36).reshape(9,4)
n94


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [155]:
result=np.vstack(tup=(n94,n64))
result

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [200, 201, 202, 203],
       [204, 205, 206, 207],
       [208, 209, 210, 211],
       [212, 213, 214, 215],
       [216, 217, 218, 219],
       [220, 221, 222, 223]])

In [156]:
#Splitting of array 
n89 = np.random.randint(low=0,high=100,size=(8,9))
n89

array([[43, 74, 71, 42, 83, 21,  6, 68, 22],
       [43,  8, 85, 62, 32, 60, 11,  1, 41],
       [26, 37, 41, 56, 39, 81, 32, 53, 35],
       [23, 29, 42, 38,  4, 93, 32, 50, 85],
       [27, 33, 91, 95, 34,  0, 91, 11, 62],
       [96, 88, 54, 89, 78, 41, 70, 85,  5],
       [ 7,  4, 16,  9, 56, 48, 43, 62, 70],
       [31,  2,  0, 15, 32, 48, 15, 61,  2]])

In [194]:
ab=np.vsplit(n89,[3,4,4])
ab[1]

array([[23, 29, 42, 38,  4, 93, 32, 50, 85]])

In [198]:
#ab


In [195]:
#random valuesabab
    

In [200]:
n = np.random.rand(150,150)
n.min()
n.max()
n.mean()

0.4991220674229164

In [207]:
n34=np.arange(12)
n34.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
n34.sum()

66

In [212]:
n34.max() 

11

In [217]:
np.linspace(1,9,9,retstep=True)

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

In [221]:
#ITraction looping on number py arraysab

In [223]:
for i in n34:
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [230]:
 for value in np.nditer(n34,order='F'):
        print(value)

0
1
2
3
4
5
6
7
8
9
10
11


In [234]:
n34
#a0,a1 = 
a0,a1=np.where(n34>5)
print(list(zip(a0,a1)))

ValueError: not enough values to unpack (expected 2, got 1)