# Numpy

In [1]:
#Numarical Python 
# general purpose Array processosing python 
# Numpy : numbers based access
#pandas : full access , Internally stores in numpy array only. 
# Numpy , pandas, matplolib , Seaborn 

In [2]:
#Numpy is core library for scintific computing in python , Gereral purpse array processing package. 

In [3]:
# Axis --->>>>> ID Array , 2 D Array , 3 D Array 
# Shape(4) shape (2,3) shape(4,3,2) can be N dimensions as every new catagory gives you new dimension 

# Creation of matrix

In [23]:
import numpy as np
mylist1 = [11,22,33,44,55,66]
n1 = np.array(mylist1)
print(n1)
print(n1.size)
print(n1.shape)
print(n1)
print(n1.dtype) # is importent
print(n1.itemsize)

[11 22 33 44 55 66]
6
(6,)
[11 22 33 44 55 66]
int64
8


In [28]:
import numpy as np
mylist1 = [11,22,33,44,55,66]
n1 = np.array(mylist1,dtype=int)
print(n1)
print(n1.size)
print(n1.shape)
print(n1)
print(n1.dtype)
print(n1.itemsize)

[11 22 33 44 55 66]
6
(6,)
[11 22 33 44 55 66]
int64
8


In [37]:
# create Manual array 
list2= [
    [11,22,33],
    [44,55,66]
]
import numpy as np
n1 = np.array(list2,dtype=int)
print(n1)
print(n1.size)
print(n1.shape)
print(n1)
print(n1.dtype)
print(n1.itemsize)

[[11 22 33]
 [44 55 66]]
6
(2, 3)
[[11 22 33]
 [44 55 66]]
int64
8


In [44]:
#create 3 d Array 
list3 = [
    [[111,121],[141,151],[171,181]],
    [[211,221],[241,251],[271,281]],
    [[311,321],[341,351],[371,381]],
    [[411,421],[441,451],[471,481]],
]
import numpy as np
n2 = np.array(list3,dtype=int)
print(n2)
print(n2.size)
print(n2.shape)
print(n2)
print(n2.dtype)
print(n2.itemsize)

[[[111 121]
  [141 151]
  [171 181]]

 [[211 221]
  [241 251]
  [271 281]]

 [[311 321]
  [341 351]
  [371 381]]

 [[411 421]
  [441 451]
  [471 481]]]
24
(4, 3, 2)
[[[111 121]
  [141 151]
  [171 181]]

 [[211 221]
  [241 251]
  [271 281]]

 [[311 321]
  [341 351]
  [371 381]]

 [[411 421]
  [441 451]
  [471 481]]]
int64
8


# arange

In [57]:

sadf

NameError: name 'sadf' is not defined

In [62]:
n2 = np.arange(12)
n34 = n2.reshape(3,4)
n34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
n5 = np.arange(12)
#arange always return 1d entitity which you could reshape using reshape Function 


n1= np.arange(48)
n642= n1.reshape(6,4,-1)
n642.shape

In [75]:
np.random.seed(23)
n1 = np.random.randint(low=0,high=100,size=(48,))
print(n1.shape)
n1

(48,)


array([83, 40, 73, 54, 31, 76, 91, 39, 90, 25, 51,  6, 45, 12, 49, 66, 75,
       85, 69, 64, 12, 21, 48, 41, 79, 90, 62, 57, 19, 33, 59, 39, 15, 36,
       65,  1, 43, 15, 86, 83, 58, 25, 66, 74, 35, 96, 56, 13])

In [76]:
np.random.seed(23)
n1 = np.random.randint(low=0,high=100,size=(6,4))
print(n1.shape)
n1

(6, 4)


array([[83, 40, 73, 54],
       [31, 76, 91, 39],
       [90, 25, 51,  6],
       [45, 12, 49, 66],
       [75, 85, 69, 64],
       [12, 21, 48, 41]])