In [43]:
! pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/1f/97/dec9dfa95cfbee631adffbeb0b7eda51ddc93a5f7e8aa8f4d95dde59e69e/tensorflow-2.16.2-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.16.2 from https://files.pythonhosted.org/packages/46/87/c3e4e9fe7c630f38a6984afdd1d4ed531ef9c74dc66b86f46f6bdd89d608/tensorflow_intel-2.16.2-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [46]:
import tensorflow as tf
import matplotlib.pyplot as plt 
import numpy as np

In [50]:
hello = tf.constant("hello world")
print(hello)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [51]:
print(hello.numpy())

b'hello world'


In [58]:
#3 data representation in tensor0d Tensor scaler


x=np.array(2)
print(x)


a = tf.constant(7)
print(a.numpy())

2
7


In [61]:
#1dscaler called 1 d vector

x1=np.array([10,32,20])
print(x1)

[10 32 20]


In [66]:
onedt=tf.constant([10,12,12])
print(onedt.numpy())

[10 12 12]


In [70]:
x2=np.array([[1,2,3],
             [4,5,6]
            ])

print(x2)

[[1 2 3]
 [4 5 6]]


In [73]:
twodt=tf.constant([[1,2,3],
                  [3,4,5],
                  [6,5,3]
                  ])

twodt.numpy()

array([[1, 2, 3],
       [3, 4, 5],
       [6, 5, 3]])

In [75]:
onedt=tf.constant([10,12,12])
print(onedt.numpy())
onedt

[10 12 12]


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 12, 12])>

In [79]:
# create a random tensor with 5 rows and 4 columns 


t1=tf.random.normal([5,4])
print(t1.numpy())

[[ 0.6289963  -1.2420212  -0.12574553  1.5478522 ]
 [ 1.9144264   1.6176194  -2.622164   -0.5425418 ]
 [ 0.15490097  1.1633137   1.6627413   1.646782  ]
 [-0.21905579 -0.1868796  -2.0398507   1.3553561 ]
 [ 0.67526996  0.13453676 -0.24245107 -1.2054206 ]]


In [84]:
t1[0,0].numpy()

0.6289963

In [86]:
!pip install keras

Defaulting to user installation because normal site-packages is not writeable


In [87]:
t2=tf.Variable(t1)

In [89]:
t2[0,0].assign(0)

<tf.Variable 'UnreadVariable' shape=(5, 4) dtype=float32, numpy=
array([[ 0.        , -1.2420212 , -0.12574553,  1.5478522 ],
       [ 1.9144264 ,  1.6176194 , -2.622164  , -0.5425418 ],
       [ 0.15490097,  1.1633137 ,  1.6627413 ,  1.646782  ],
       [-0.21905579, -0.1868796 , -2.0398507 ,  1.3553561 ],
       [ 0.67526996,  0.13453676, -0.24245107, -1.2054206 ]],
      dtype=float32)>

In [93]:
a=tf.constant([1,2])
b=tf.constant([3,3])
c=tf.constant([3,3])
print(tf.add(a,b).numpy())

[4 5]


In [95]:
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

# Access tensors value.
print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 2
sum = 15


In [98]:
T1 =tf.constant([[1, 2, 3],    
              [4, 5, 8]])
T2 =tf.constant (20)  

T3=T1+T2
print(T3)

tf.Tensor(
[[21 22 23]
 [24 25 28]], shape=(2, 3), dtype=int32)


In [104]:
a=tf.Variable(np.random.randint(1,11,[3,2]))
b=tf.Variable(np.random.randint(1,11,[3,3]))

In [106]:
print(a)
print(b)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 1,  9,  6],
       [ 7,  8,  8],
       [10,  8,  5]])>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[2, 7, 1],
       [5, 7, 7],
       [8, 8, 7]])>


In [108]:
a*b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2, 63,  6],
       [35, 56, 56],
       [80, 64, 35]])>

In [110]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 95, 118, 106],
       [118, 169, 119],
       [100, 166, 101]])>

In [115]:
a=tf.Variable(np.random.randint(1,11,[3,2]))
a

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 4, 10],
       [ 4,  5],
       [ 4,  4]])>

In [117]:
t12=tf.reshape(a,[2,3])
t12

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 10,  4],
       [ 5,  4,  4]])>

In [121]:
import ipaddress

# Original CIDR block
original_cidr = ipaddress.ip_network('10.64.0.0/10')

# Calculate the /16 subnet
subnet_16 = list(original_cidr.subnets(new_prefix=16))[0]

# Calculate the /21 subnet
# Ensuring the /21 subnet does not overlap with the /16 subnet
# We take the next available /21 subnet after the /16 range
subnet_21_start = list(subnet_16.hosts())[-1] + 1
subnet_21 = ipaddress.ip_network(f'{subnet_21_start}/21', strict=False)

# Calculate the /27 subnet
# Ensuring the /27 subnet does not overlap with the /21 subnet
# We take the next available /27 subnet after the /21 range
subnet_27_start = list(subnet_21.hosts())[-1] + 1
subnet_27 = ipaddress.ip_network(f'{subnet_27_start}/27', strict=False)

# Print the new subnets
print(f"Subnet /16: {subnet_16}")
print(f"Subnet /21: {subnet_21}")
print(f"Subnet /27: {subnet_27}")


Subnet /16: 10.64.0.0/16
Subnet /21: 10.64.248.0/21
Subnet /27: 10.64.255.224/27
