In [2]:
import pandas as pd 
import numpy as np

In [42]:
A = np.array([[7,3],[5,6],[7,4]])
A

array([[7, 3],
       [5, 6],
       [7, 4]])

In [43]:
U,S,V = np.linalg.svd(A)

In [44]:
U.shape


(3, 3)

In [45]:
U

array([[-0.56196439,  0.54834095, -0.61928848],
       [-0.56479059, -0.80136405, -0.19704634],
       [-0.6043241 ,  0.23903528,  0.76003587]])

In [33]:
a = np.dot(np.dot(U[:,:2],np.diag(S)),V)

In [46]:
a

array([[7., 3.],
       [5., 6.],
       [7., 4.]])

In [47]:
np.diag(S)

array([[13.299045  ,  0.        ],
       [ 0.        ,  2.67121732]])

In [48]:
b = np.dot(np.dot(U[:,:1],S[0]),V[:1,:])
b

array([[6.17484917, 4.2101996 ],
       [6.20590337, 4.2313733 ],
       [6.6402965 , 4.52755572]])

In [49]:
S[0]/np.sum(S) ## this is the information that we have captured. 

0.8327380437166624

In [50]:
S[1]/np.sum(S) ## this is the information that is lost

0.16726195628333762

In [51]:
A = np.array([
    [1,1,1,0,0],
    [3,3,3,0,0],
    [4,4,4,0,0],
    [5,5,5,0,0],
    [0,2,0,4,4],
    [0,0,0,5,5],
    [0,1,0,2,2]
])

In [52]:
U,S,V= np.linalg.svd(A)

In [53]:
S.round(2)

array([12.48,  9.51,  1.35,  0.  ,  0.  ])

In [54]:
a_ = np.dot(np.dot(U[:,:3],np.diag(S[:3])),V[:3,:])
a_

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -1.45688500e-16, -1.45688500e-16],
       [ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
        -2.03558451e-16, -2.03558451e-16],
       [ 4.00000000e+00,  4.00000000e+00,  4.00000000e+00,
        -1.12552469e-16, -1.12552469e-16],
       [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
        -7.70317187e-17, -7.70317187e-17],
       [ 2.40680179e-16,  2.00000000e+00, -8.84928174e-16,
         4.00000000e+00,  4.00000000e+00],
       [ 1.18292943e-16,  3.99091262e-16, -4.65938276e-16,
         5.00000000e+00,  5.00000000e+00],
       [ 1.20340089e-16,  1.00000000e+00, -4.42464087e-16,
         2.00000000e+00,  2.00000000e+00]])

In [55]:
a_.round(2)

array([[ 1.,  1.,  1., -0., -0.],
       [ 3.,  3.,  3., -0., -0.],
       [ 4.,  4.,  4., -0., -0.],
       [ 5.,  5.,  5., -0., -0.],
       [ 0.,  2., -0.,  4.,  4.],
       [ 0.,  0., -0.,  5.,  5.],
       [ 0.,  1., -0.,  2.,  2.]])

In [56]:
a_2 = np.dot(np.dot(U[:,:2],np.diag(S[:2])),V[:2,:])

In [57]:
a_2.round(2)

array([[ 0.99,  1.01,  0.99, -0.  , -0.  ],
       [ 2.98,  3.04,  2.98, -0.  , -0.  ],
       [ 3.98,  4.05,  3.98, -0.01, -0.01],
       [ 4.97,  5.06,  4.97, -0.01, -0.01],
       [ 0.36,  1.29,  0.36,  4.08,  4.08],
       [-0.37,  0.73, -0.37,  4.92,  4.92],
       [ 0.18,  0.65,  0.18,  2.04,  2.04]])

In [58]:
(S[0]+S[1])/S.sum()

0.9423377396381534

In [59]:
S[2]/S.sum()

0.05766226036184652

In [60]:
A1 = pd.DataFrame(A,columns=['m1','m2','m3','m4','m5'],index=['u1','u2','u3','u4','u5','u6','u7'])

In [61]:
A1

m1  m2  m3  m4  m5
u1   1   1   1   0   0
u2   3   3   3   0   0
u3   4   4   4   0   0
u4   5   5   5   0   0
u5   0   2   0   4   4
u6   0   0   0   5   5
u7   0   1   0   2   2

In [62]:
pd.DataFrame(U[:,:2].round(2),columns=['concept1','concept2'],
            index=['u1','u2','u3','u4','u5','u6','u7'])


concept1  concept2
u1     -0.14     -0.02
u2     -0.41     -0.07
u3     -0.55     -0.09
u4     -0.69     -0.12
u5     -0.15      0.59
u6     -0.07      0.73
u7     -0.08      0.30

In [63]:
# v matrix concept and movies

In [65]:
V

array([[-5.62258405e-01, -5.92859901e-01, -5.62258405e-01,
        -9.01335372e-02, -9.01335372e-02],
       [-1.26641382e-01,  2.87705846e-02, -1.26641382e-01,
         6.95376220e-01,  6.95376220e-01],
       [-4.09667482e-01,  8.04791520e-01, -4.09667482e-01,
        -9.12571001e-02, -9.12571001e-02],
       [-7.07106781e-01,  1.11022302e-16,  7.07106781e-01,
         5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00, -4.87723954e-17,  4.87723954e-17,
        -7.07106781e-01,  7.07106781e-01]])

In [ ]:
pd.DataFrame(V[:,:2].round(2),columns=['concept1','concept2'],
            index=['u1','u2','u3','u4','u5','u6','u7'])
