<table align="center" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Inclass-Lab  <br>(Session 3 & 4)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**
6. **[Data Structures with Examples](#Data_Structures)**
7. **[Create and Manipulate the DataFrames](#create_manipulate)**
8. **[Sort](#sorting)**
9. **[Rank](#ranking)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [11]:
import numpy as np
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
onedarray=np.array(weights)
onedarray[onedarray > 68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [26]:
np.random.seed(23)
np1=np.random.randint(20,40,10)
np1

array([39, 26, 28, 29, 28, 33, 32, 27, 39, 26])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [48]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
np2=np.array(A)
np2.sum(axis=0)

array([15, 25, 13])

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [75]:
mylist1=np.arange(20)
np4=mylist1.reshape(5,4)
type(np4)
np4[1,0:5]

array([4, 5, 6, 7])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [110]:
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 
bmi=[]
for i in range(0,len(weights)):
    bmi.append(weights[i]//heights[i])
print('your BMi chart is :',bmi)

your BMi chart is : [35.0, 39.0, 32.0, 37.0, 43.0, 36.0, 36.0]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [133]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
array1.append(([5,7]))
array1

[[[3, 4], [8, 2], [5, 9]], [5, 7]]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [138]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
np1=np.array(M)
np1.transpose()

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [142]:
A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]
np1=np.array(A1)
np2=np.array(A2)
np3=np.vstack((np1,np2))
np3

array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [143]:
A2 = [[15, 54], [39, 56]]
A1 = [[-81, 75, 40], [27, 67, 52]]

np1=np.array(A1)
np2=np.array(A2)
np3=np.hstack((np2,np1))
np3

array([[ 15,  54, -81,  75,  40],
       [ 39,  56,  27,  67,  52]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [157]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
np1=np.array(B)
np1
np2=np.hsplit(np1,2)
print(np2[0])
print(np2[1])

[[ 8  7]
 [ 2 -3]
 [ 8  5]]
[[ 0  9]
 [ 5 10]
 [-1  3]]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [163]:
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]
L3=[]
for i in range(0,len(L1)):
    for j in range(0,len(L2)):
        if i == j:
         L3.append((L1[i],L2[j]))
L3  

[(45, 21), (67, 52), (56, 64), (71, 10), (54, 49), (62, 74), (56, 26)]

<a id='Data_Structures'></a>
## 6. Data Structures with Examples:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to create a dataframe from list of lists
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the below nested list:**<br>

        data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]

In [169]:
data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]
type(data)
import pandas as pd
df1=pd.DataFrame(data)
df1

0   1
0  Joy  21
1  Mia  15
2  Sam  14

<a id='create_manipulate'></a>
## 7. Create and Manipulate the DataFrames:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Split the 'Name' column into two separate columns as First_Name and Last_Name </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Salary</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>3200</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>4500</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>3600</td>
</tr>
<tr>
<td>James Smith</td>
<td>5596</td>
</tr>
   
</table>

In [188]:
import pandas as pd
list1={'name':['Emma Larter','Mia Junior','Sophia Depp','James Smith'],'salary':[3200,4500,3600,5596]}
list1
df2=pd.DataFrame(list1)
df2[['First', 'Last']] = df2['name'].str.split(expand=True)
df2


name  salary   First    Last
0  Emma Larter    3200    Emma  Larter
1   Mia Junior    4500     Mia  Junior
2  Sophia Depp    3600  Sophia    Depp
3  James Smith    5596   James   Smith

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to select the rows where the sales are higher than 60000 for Mumbai </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [190]:
df1=pd.read_csv('assignment.csv')
df1

FileNotFoundError: [Errno 2] No such file or directory: 'assignment.csv'

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a program to replace the 'Store' column with the values A, B, C, and D with Store_A,  Store_B, Store_C and Store_D respectively </b>  
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [15]:
# type your code here

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a program to insert a given column at the second position in a dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
   
</table>

**Add the variable 'Salary' as second column**<br>
            
            Salary = [35000, 24000, 55000, 40000]

In [16]:
# type your code here

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to get the third observation of the given dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
</table>    

In [17]:
# type your code here

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to count total sales per store </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [18]:
# type your code here

<a id='sorting'></a>
## 8. Sort

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Write a program to sort the dataframe by 'Store' in ascending order and by 'Sales' in descending order simultaneously
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [19]:
# type your code here

<a id='ranking'></a>
## 9. Rank

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Rank the dataframe in descending order of sales by each store
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [20]:
# type your code here